### ISSUE TITLE
What should be normal values of the Link quality between the coordinator cc2652p2-tcp-zigbee and a power adapter seeing each other

### ISSUE THREAD

**Issue by ericvb** [codm/cc2652p2-tcp-zigbee#6]
Never payed attention to it because it did work. But now I have a Sonoff doorsensor who goes offline some hours after his pairing.
After making my homework about Link quality, I should expect that between the Z5 power adapter and the coordinator, I should see above 150 as link quality...

I know that there are hundred of articles about How to make your Zigbee network performant?
But for example I see between the Lightstrip and the Z5, 179/154. There is a brick wall between them.
Between the radiator endpoints and the lightstrip there is a concrete floor and brick wall, very good link quality
Between Z1, Z5 and lightstrip, very good Link quality (brick wall between them)
So, in my opinion, the Zigbee signal is not disturbed by e.g. my wifi signal (I payed attention to configure different channels)
So why these bad link quality values to the coordinator? The coordinator is placed a 0.5m under the ceiling of Floor 0.

See attachment for the network map.
![Zigbee map network](https://github.com/codm/cc2652p2-tcp-zigbee/assets/3419875/83ffdfe8-c6ff-4d11-867e-20d42058700f)

**Comment by codmpm** [comment]
Hey Eric,

not sure if we can help here as we simply use Koenkk's Z-Stack Firmware on a CC2652P2. As far as I know the linquality is determined by the ZigBee-Mesh itself, but I'm no expert on this. 
Maybe you can ask this here: https://github.com/Koenkk/Z-Stack-firmware/issues

Cheers,
Patrik

**Comment by ericvb** [comment]
Hi Patrick,

But when you have tested your hardware, what where the Link quality values?
My device is 3m away from the coordinator. My device is 0.5m from the floor and the Coordinator is placed 0.5m from the ceiling.
I should expect high link quality values :-(

Following your link to Koenkk, I found following issue : https://github.com/Koenkk/Z-Stack-firmware/discussions/474
But I did receive my coordinator January this year, so I should still have a 2022 firmware version.
Can I see with that ZigStarr multitool the installed firmware version of my coordinator?

Regards,
Eric

**Comment by codmpm** [comment]
Of course you can. See the description here to update the firmware: https://github.com/codm/cc2652p2-tcp-zigbee#update
Of course we will re-do this if anything goes wrong for your free of charge.

![grafik](https://github.com/codm/cc2652p2-tcp-zigbee/assets/9745239/ac141bcb-6b23-426b-a46a-b1084cbf6e47)
This is what it looks on my own installation using the TCP ZigBee Coordinator with with Z-Stack Firmware `20230507`.
The Coordinator and sz-bett are 2-3m appart through reincorfced concrete. wz-steckd is 4-5m through a brick wall.
Keep in mind what hinders 2.4GHz signals (e.g. dry wall, etc.).

**Comment by ericvb** [comment]
A follow-up.

I finally didn't update the coordinator due to the problems mentioned in https://github.com/Koenkk/Z-Stack-firmware/discussions/474
I bought an other door sensor, a white Chinese product, a TS0203 based one (_TZ3000_oxslv1c9).
This sensor does not go offline in the existing described configuration (see opening first issue message)

The Sonoff door sensor is now on my desk, in visual sight of view of a router. The sensor does go still offline after some time, but opening the sensor makes him go online again automatically.
So conclusion, the Sonoff sensor is working, his going offline is probably by design, but if too far away from a coordinator or router, the sensor will not come back online if his state is changing.

I'm closing now this ticket. Thanks for your time.
